package edu.ucam.clients.frames;



import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import edu.ucam.domain.Club;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 * <p>
*Esta es la clase en la que se crea una tabla 
*con los clubes que hay registrados.
*</p>
*/

public class ClubTableView extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	
	ArrayList<Club> lista = new ArrayList<>();
    /**
     * 
     * @param club
     * Inicia los componentes
     */
    public ClubTableView(Club club)
    {
    	initComponents();
    	this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setAlwaysOnTop(true);
        
        lista = new ArrayList<Club>();
        this.lista.add(club);

        this.mostrarDatos();
        this.setAlwaysOnTop(false);
    }
    
    /**
     * 
     * @param clubes
     * Muestra los datos en la tabla
     */
    public ClubTableView(ArrayList<Club> clubes) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setAlwaysOnTop(true);
        
        if(clubes == null)
        	clubes = new ArrayList<Club>();
        lista = clubes;
        
        this.mostrarDatos();
        this.setAlwaysOnTop(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    /**
     * Inicializa los componentes
     */
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jTableView.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"Id", "Nombre", "Num Jugadores"
        	}
        ));
        jTableView.getColumnModel().getColumn(0).setMaxWidth(75);
        jTableView.getColumnModel().getColumn(2).setResizable(false);
        jTableView.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableView.getColumnModel().getColumn(2).setMaxWidth(100);
        jScrollPane1.setViewportView(jTableView);
        
        JLabel lblNewLabel = new JLabel("CLUBES REGISTRADOS");
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(244)
        					.addComponent(lblNewLabel)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(12, Short.MAX_VALUE)
        			.addComponent(lblNewLabel)
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 286, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Muestra los datos de los clubes
     */
    public void mostrarDatos(){
    	
    	 DefaultTableModel model = (DefaultTableModel) this.jTableView.getModel(); 
    	if (model.getRowCount() > 0) {
    	    for (int i = model.getRowCount() - 1; i > -1; i--) {
    	    	model.removeRow(i);
    	    }
    	}
    	 if(lista!=null)
        for (Club o : lista) {
        	
        	model.addRow(
        			new Object[]
    					{
    							o.getId(),
    							o.getNombre(),
    							o.getJugadores().size()
    					});
        }
        jTableView.setModel(model);
        
    }
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
        	
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClubTableView(new ArrayList<Club>()).setVisible(true);
            }
        });
    }
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableView;
}